Unpin openfermion, needed for tests
Without this change, the following test error will occur:

libs/solvers/python/tests/test_jordan_wigner.py::test_ground_state -
AttributeError: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.

This message originates from openfermion, which we had previously pinned
to 1.6.1. This change unpins that to allow it to advance to 0.7.

Signed-off-by: Ben Howe <bhowe@nvidia.com>